### ISSUE TITLE
"Could not find character" - Final Fantasy XIV Twitch Eorzea Profile Doesn't Work

### ISSUE THREAD

**Issue by MUGENWITCHER** [bdejesus/twitch-xiv-profile#13]
**Describe the bug**
Hello, I'm MUGENWITCHER on Twitch and I used the Eorzea Profile Extension as Panel in my About. But recently it's giving me problems, and really don't know if I am the problem or the extension is having issues.
![problemhere](https://github.com/bdejesus/twitch-xiv-profile/assets/153392735/9c4c53d1-e61a-4a59-aee8-2256aec7125a)

**Comment by FredZorilla** [comment]
Hello, I'm Moushgard on twitch and got the same problem here : https://na.finalfantasyxiv.com/lodestone/character/3846388/

**Comment by bdejesus** [comment]
Unfortunately, it looks like XIVAPI's service that provides the character profiles is being retired and is why this is no longer working. I'll need to look into other ways of getting character profile data, but right now there's not really a short term fix.

**Comment by MUGENWITCHER** [comment]
Ohhh this is sad then T_T I hope we can get something like the extention, it was very cute

**Comment by bdejesus** [comment]
I've submitted an update to fix this and it will go live as soon as it's approved. 

This update now requests character data from an alternative API and to keep requests down, updates to character data (gear changes, etc) will now only happen on the configuration page when you load your character ID.

**Comment by bdejesus** [comment]
Reopening this issue -- the fix is under review by Twitch, will post an update when it goes live.

**Comment by MUGENWITCHER** [comment]
Ohhh thank you <3

**Comment by bdejesus** [comment]
Twitch just approved the updated plugin, this issue should now be resolved.

**Comment by MUGENWITCHER** [comment]
Aaaaaaa Thank you for the information you're so kinddd have a good dayyy! <3
