### ISSUE TITLE
Eorzea Profile extension does not detect my character

### ISSUE THREAD

**Issue by Twojkszmar** [bdejesus/twitch-xiv-profile#14]
**Describe the bug**
Extension is unable to find my character upon providing it with character ID or full link to Lodestone website. The extension returns the following error: "Could not find character. Please make sure you entered the correct ID or URL."

**To Reproduce**
1. Go to Twitch dashboard -> Extensions
2. Search for "Eorzea Profile" extension
3. Click "Install" 
4. On the configuration screen provide extension with Character ID or Character Profile URL
5. Click "LOAD PROFILE"
6. Observe the issue

**Expected behavior**
Extension cannot find the profile and returns the error: Could not find character. Please make sure you entered the correct ID or URL.

**Screenshots**
![image](https://github.com/bdejesus/twitch-xiv-profile/assets/23724296/52e5a808-e528-4219-9051-6bb303bdd326)

**Browser Info (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 120.0.2210.91

**Comment by bdejesus** [comment]
👉🏼 https://github.com/bdejesus/twitch-xiv-profile/issues/13
