### ISSUE TITLE
Can't load any of my profiles

### ISSUE THREAD

**Issue by rwmfleming** [bdejesus/twitch-xiv-profile#15]
**Describe the bug**
I am unable to load any of my characters. Just keeps telling me it's unable to load

I have copied and pasted the url and tried the id and nothing happens

**Comment by tassietaker** [comment]
I am also having this issue. It's telling me that the character cannot be found.

**Comment by bdejesus** [comment]
Thanks for reporting, there's a fix incoming within the next few days.

Updates will be posted on https://github.com/bdejesus/twitch-xiv-profile/issues/13
