### ISSUE TITLE
Eorzean profile extension not working correctly.

### ISSUE THREAD

**Issue by smokey5182** [bdejesus/twitch-xiv-profile#25]
Profile will not load. When I enter the url or character id to configure it says not found. It was working fine before now I dont know why it isnt working. Please assist.

**Comment by ndblair** [comment]
Having the same issue

**Comment by XBLIVION** [comment]
Same issues with the Alternative API ?

**Comment by XBLIVION** [comment]
[ffxivapi](https://github.com/roobre/ffxivapi) ?

**Comment by smokey5182** [comment]
The twitch Eorzean profile extension is what Im referring too. I dont even
know what the api thing is.

**Comment by bdejesus** [comment]
Hey all, this extension is dependent on https://xivapi.com/ which has stopped supporting the endpoint used to get character profiles. There's already a patch version submitted for review to twitch, but unfortunately, they've paused all reviews until they've reorganized:

> Reviews for Extensions, organizations, games, and chatbot verification are temporarily paused while we revise our processes. We are working to resume reviews as quickly as possible and will share updates with you shortly. Thank you for your patience and understanding. 

- https://dev.twitch.tv/docs/

So until they resume this process, there's not much we can do. Sorry for the inconvenience.

**Comment by bdejesus** [comment]
This should now be resolved (more info: https://github.com/bdejesus/twitch-xiv-profile/issues/13)
