### ISSUE TITLE
Problems loading Eorzea profile on Twitch Extension

### ISSUE THREAD

**Issue by DinoInsanity** [bdejesus/twitch-xiv-profile#27]
Every time I try to load my Eorzea profile it has an error message saying it cant find it. I followed the extension's instructions and copied my Lodestone link for my profile but I still get the same message.
![image_2024-04-19_171140800](https://github.com/bdejesus/twitch-xiv-profile/assets/167584840/380b1fce-02bb-44e7-b108-5e7ab0c31139)

**Comment by bdejesus** [comment]
This should now be resolved (more info: https://github.com/bdejesus/twitch-xiv-profile/issues/13)
