### ISSUE TITLE
Needing precise information on how to use Eorzea Profile

### ISSUE THREAD

**Issue by Gambit0328** [bdejesus/twitch-xiv-profile#28]
**Describe the bug**

I am very much aware that this may be user error to the extreme but I am not sure what to do. I am trying to load my character profile on to the extension and all I get is "Could not find character. Please make sure you entered the correct ID or URL. 

https://na.finalfantasyxiv.com/lodestone/character/47519682/  This is the url for my profile on the lodestone. I copied and pasted and got the same error message each time. I even used just the numbers 4751682 as an id number same result. 

Please assist?
I am on Windows 10. and using Google Chrome as my broswer.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser Info (please complete the following information):**
 - OS: [e.g. Windows/Mac]

**Additional context**

**Comment by bdejesus** [comment]
This should now be resolved (more info: https://github.com/bdejesus/twitch-xiv-profile/issues/13)
